# Generated by Django 5.2.8 on 2025-11-19 14:23

import OngAmp.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adotante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter apenas números (11 dígitos).', regex='^\\d{11}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ ]+$', 'Nome deve conter apenas letras')])),
                ('coloracao', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^[A-Za-zÀ-ÿ ]+$', 'Cor deve conter apenas letras')])),
                ('descricao', models.CharField(max_length=255)),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino')], default='M', max_length=1)),
                ('categoria_pet', models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato')], default='C', max_length=1)),
                ('idade', models.CharField(choices=[('FILHOTE', 'Filhote'), ('ADULTO', 'Adulto')], default='ADULTO', max_length=8)),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], default='M', max_length=1)),
                ('is_castrado', models.CharField(choices=[('C', 'Castrado'), ('NC', 'Não Castrado')], default='C', max_length=2)),
                ('fotos_pet', models.ImageField(blank=True, null=True, upload_to='img_pets/', validators=[OngAmp.validators.validar_imagem])),
                ('is_condicao_especial', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('adotante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adocoes', to='OngAmp.adotante')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adocoes', to='OngAmp.pet')),
                ('voluntario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adocoes', to='OngAmp.voluntario')),
            ],
        ),
    ]
