# Generated by Django 5.2.8 on 2025-11-29 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTransparencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('arquivo', models.FileField(upload_to='transparencia_pdfs/', verbose_name='Arquivo PDF')),
                ('categoria', models.CharField(choices=[('ESTATUTO', 'Estatuto e Atas'), ('FINANCEIRO', 'Prestação de Contas (Financeiro)'), ('ATIVIDADES', 'Relatórios de Atividades'), ('CERTIDOES', 'Certidões Negativas')], default='FINANCEIRO', max_length=20)),
                ('data_publicacao', models.DateField(default=datetime.datetime.now, verbose_name='Data de Referência')),
            ],
            options={
                'verbose_name': 'Documento de Transparência',
                'verbose_name_plural': 'Transparência',
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
