# Generated by Django 5.2.8 on 2025-11-29 15:30

import OngAmp.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0002_documentotransparencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='fotos_pet',
        ),
        migrations.AddField(
            model_name='pet',
            name='is_adotado',
            field=models.BooleanField(default=False, verbose_name='Já foi adotado?'),
        ),
        migrations.CreateModel(
            name='FotoPet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='img_pets/', validators=[OngAmp.validators.validar_imagem])),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='OngAmp.pet')),
            ],
        ),
    ]
