# Generated by Django 5.2.8 on 2025-11-29 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0003_remove_pet_fotos_pet_pet_is_adotado_fotopet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentotransparencia',
            name='categoria',
            field=models.CharField(choices=[('MENSAL', 'Prestação de Contas Mensal'), ('ANUAL', 'Prestação de Contas Anual'), ('ESTATUTO', 'Estatuto e Atas'), ('ATIVIDADES', 'Relatórios de Atividades'), ('CERTIDOES', 'Certidões Negativas'), ('OUTROS', 'Outros Documentos')], default='MENSAL', max_length=20),
        ),
    ]
