# Generated by Django 5.2.8 on 2025-11-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0004_alter_documentotransparencia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='coloracao',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='pet',
            name='descricao',
            field=models.TextField(verbose_name='História do Pet'),
        ),
    ]
