# Generated by Django 5.2.8 on 2025-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0005_alter_pet_coloracao_alter_pet_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='adotante',
            name='email',
            field=models.EmailField(default='', max_length=100, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adotante',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, verbose_name='Endereço Completo'),
        ),
        migrations.AddField(
            model_name='adotante',
            name='telefone',
            field=models.CharField(default='', max_length=15, verbose_name='WhatsApp/Telefone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(choices=[('F', 'Fêmea'), ('M', 'Macho')], default='M', max_length=1),
        ),
    ]
