# Generated by Django 5.2.8 on 2025-11-29 21:37

import OngAmp.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OngAmp', '0006_adotante_email_adotante_endereco_adotante_telefone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adocao',
            options={'verbose_name': 'Registro de Adoção', 'verbose_name_plural': 'Registro de Adoções'},
        ),
        migrations.AlterModelOptions(
            name='adotante',
            options={'verbose_name': 'Adotante', 'verbose_name_plural': 'Adotantes'},
        ),
        migrations.AlterModelOptions(
            name='fotopet',
            options={'verbose_name': 'Foto do Pet', 'verbose_name_plural': 'Fotos dos Pets'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'Pet', 'verbose_name_plural': 'Pets (Animais)'},
        ),
        migrations.AlterModelOptions(
            name='voluntario',
            options={'verbose_name': 'Voluntário', 'verbose_name_plural': 'Voluntários'},
        ),
        migrations.AddField(
            model_name='adotante',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voluntario',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Adoção'),
        ),
        migrations.AlterField(
            model_name='adocao',
            name='voluntario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adocoes', to='OngAmp.voluntario', verbose_name='Voluntário Responsável'),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter apenas números (11 dígitos).', regex='^\\d{11}$')], verbose_name='CPF (Apenas números)'),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='adotante',
            name='telefone',
            field=models.CharField(max_length=20, verbose_name='WhatsApp/Telefone'),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='categoria',
            field=models.CharField(choices=[('MENSAL', 'Prestação de Contas Mensal'), ('ANUAL', 'Prestação de Contas Anual'), ('ESTATUTO', 'Estatuto e Atas'), ('ATIVIDADES', 'Relatórios de Atividades'), ('CERTIDOES', 'Certidões Negativas'), ('OUTROS', 'Outros Documentos')], db_index=True, default='MENSAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentotransparencia',
            name='data_publicacao',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data de Referência'),
        ),
        migrations.AlterField(
            model_name='fotopet',
            name='imagem',
            field=models.ImageField(upload_to='img_pets/', validators=[OngAmp.validators.validar_imagem], verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='fotopet',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='OngAmp.pet', verbose_name='Pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='categoria_pet',
            field=models.CharField(choices=[('C', 'Cachorro'), ('G', 'Gato')], db_index=True, default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='coloracao',
            field=models.CharField(max_length=30, verbose_name='Coloração'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='descricao',
            field=models.TextField(help_text='Conte um pouco sobre o resgate e a personalidade do animal.', verbose_name='História do Pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_adotado',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Já foi adotado?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_castrado',
            field=models.CharField(choices=[('C', 'Castrado'), ('NC', 'Não Castrado')], default='C', max_length=2, verbose_name='É castrado?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_condicao_especial',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='N', max_length=1, verbose_name='Tem condição especial?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Pet'),
        ),
        migrations.AlterField(
            model_name='voluntario',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome do Voluntário'),
        ),
    ]
