"""
Django settings for OngAmpaSite project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-dy!k1vuis6zep3zdy79o0%3!x7fg^8r^0*d^=3cn-w)-#^d-!u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'OngAmp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
  
]

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

ROOT_URLCONF = 'OngAmpaSite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'OngAmpaSite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'pt-br'  # Mudei para português para o Admin ficar traduzido!
TIME_ZONE = 'America/Sao_Paulo' # Ajuste o fuso para o Brasil
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# URL para acessar os arquivos no navegador
MEDIA_URL = '/media/'


# Media files (Uploads) - Mantenha APENAS esta definição
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuração de E-mail (Desenvolvimento)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'site@ongampa.com.br'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==================================
# CONFIGURAÇÕES DO JAZZMIN (ADMIN)
# ==================================
JAZZMIN_SETTINGS = {
    "site_title": "Admin AMPA",
    "site_header": "AMPA",
    "site_brand": "Gestão AMPA",
    "welcome_sign": "Bem-vindo ao Painel da ONG AMPA",
    "copyright": "AMPA Mirassol",
    "site_logo": "img/LogoAmpa-new.png", 
    "login_logo": "img/LogoAmpa-new.png",
    
    # CSS Customizado (Certifique-se que o arquivo existe em static/css/admin-custom.css)
    "custom_css": "css/admin-custom.css",
    
    "search_model": "OngAmp.Pet",
    
    "topmenu_links": [
        {"name": "Ver Site", "url": "index", "permissions": ["auth.view_user"]},
        {"app": "OngAmp"},
    ],

    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "OngAmp.Pet": "fas fa-paw",
        "OngAmp.Adocao": "fas fa-heart",
        "OngAmp.Adotante": "fas fa-user-friends",
        "OngAmp.Voluntario": "fas fa-hands-helping",
        "OngAmp.DocumentoTransparencia": "fas fa-file-invoice-dollar",
        "OngAmp.FotoPet": "fas fa-camera",
    },
    
    "order_with_respect_to": ["OngAmp", "auth"],
    "show_ui_builder": False, # Desativei pois já configuramos o tema
}

JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",
}